[workspace]
members = ["src/crates/Activations",
    "src/crates/Algorithms",
    "src/crates/Dataloader",
    "src/crates/Encoders",
    "src/crates/MachineLearnModels",
    "src/crates/Maths",
    "src/crates/Metrics",
    "src/crates/ModelSaveLoad",
    "src/crates/NeuralNets",
    "src/crates/Optimisers",
    "src/crates/Serving",
    "src/crates/Tensors",
    "src/crates/Transforms",
    "src/crates/Utilities",
    "src/crates/Activations",
]

[package]
name = "AiuWlz"
description = ""
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
license-file = "LICENSE"

[dependencies]