use Utilities::Utilities::Quartile;

use crate::dtype::{Element, Float};
use crate::error::{TensorResult, TensorError};
use crate::layout::normalize_dim;
use crate::par;
use crate::storage::Storage;
use crate::tensor::Tensor;
use std::cmp::Ordering;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReduceOp { Sum, Max, Min }

/// Sort a Element array
fn sorted<T: Element>(s: &[T]) -> Vec<T> {
    let mut v = s.to_vec();
    v.sort_by(|a, b| a.partial_cmp(b).unwrap_or(Ordering::Equal));
    v
}

/// Normal percentile calculation
fn percentile_of<T: Element>(s: &[T], p: f64) -> T {
    if s.is_empty() { return T::zero(); }
    let v = sorted(s);
    let rank = (p / 100.0).clamp(0.0, 1.0) * (v.len() - 1) as f64;
    let (lo, hi) = (rank.floor() as usize, rank.ceil() as usize);
    let frac = rank - lo as f64;
    T::from_f64(v[lo].to_f64() * (1.0 - frac) + v[hi].to_f64() * frac)
}

/// Calculate mode
fn mode_of<T: Element>(s: &[T]) -> T {
    let v = sorted(s);
    if v.is_empty() { return T::zero(); }
    let (mut best, mut best_n, mut cur_n) = (v[0], 1_usize,1_usize);
    for i in 1..v.len() {
        cur_n = if v[i] == v[i - 1] { cur_n + 1 } else { 1 };
        if cur_n > best_n { best_n = cur_n; best = v[i]; }
    }
    best
}

impl<T: Element> Tensor<T> {
    /// Reduction over dim with an arbitrary slice → value function
    // Generated by AI
    pub fn reduce_with<R: Element>(&self, dim: isize, keepdim: bool, f: impl Fn(&[T]) -> R + Sync + Send) -> TensorResult<Tensor<R>> {
        let d = normalize_dim(dim, self.ndim())?;
        let n = self.shape()[d];
        let data = self.movedim_last(d)?.host_data()?.into_owned();
        let mut out_shape = self.shape().to_vec();
        out_shape.remove(d);
        let outer: usize = out_shape.iter().product();
        let mut out = vec![R::zero(); outer];
        if n == 0 {
            out.iter_mut().for_each(|o| *o = f(&[]));
        } else {
            par::for_each_row(&mut out, 1, n, |i, r| r[0] = f(&data[i * n..(i + 1) * n]));
        }
        let t = Tensor::from_vec(out, &out_shape)?;
        let t = if R::CUDA_TYPE.is_some() { t.to_device(self.device())? } else { t };
        if keepdim { t.unsqueeze(d as isize) } else { Ok(t) }
    }

    /// Internal fn to apply sum,max and min
    fn reduce_op(&self, dim: isize, keepdim: bool, op: ReduceOp) -> TensorResult<Self> {

        match &*self.storage {
            Storage::Cpu(_) => {
                match op {
                    ReduceOp::Sum => self.reduce_with(dim, keepdim, |s| s.iter().fold(T::zero(), |a, &b| a + b)),
                    ReduceOp::Max => self.reduce_with(dim, keepdim, |s| s.iter().fold(T::lowest(), |a, &b| if b > a { b } else { a })),
                    ReduceOp::Min => self.reduce_with(dim, keepdim, |s| s.iter().fold(T::highest(), |a, &b| if b < a { b } else { a })),
                }
            },
            #[cfg(feature = "cuda")]
            Storage::Cuda(_) => {
                let d = normalize_dim(dim, self.ndim())?;
                crate::cuda::reduce(self, d, op, keepdim)
            }
        }
    }

    /// Sum over all elems over a dim
    /// The keepdim flag should be set to true for proper broadcasting(i.e set flag true if the resultant tensor will have ops done on it)
    pub fn sum(&self, dim: isize, keepdim: bool) -> TensorResult<Self> { self.reduce_op(dim, keepdim, ReduceOp::Sum) }

    /// Max elem over a dim in a Tensor
    /// The keepdim flag should be set to true for proper broadcasting(i.e set flag true if the resultant tensor will have ops done on it)
    pub fn max(&self, dim: isize, keepdim: bool) -> TensorResult<Self> { self.reduce_op(dim, keepdim, ReduceOp::Max) }

    /// Min elem over a dim in a Tensor
    /// The keepdim flag should be set to true for proper broadcasting(i.e set flag true if the resultant tensor will have ops done on it)
    pub fn min(&self, dim: isize, keepdim: bool) -> TensorResult<Self> { self.reduce_op(dim, keepdim, ReduceOp::Min) }

    /// Product over all elems over a dim
    /// The keepdim flag should be set to true for proper broadcasting(i.e set flag true if the resultant tensor will have ops done on it)
    pub fn prod(&self, dim: isize, keepdim: bool) -> TensorResult<Self> { self.via_host(|t| t.reduce_with(dim, keepdim, |s| s.iter().fold(T::one(), |a, &b| a * b))) }

    /// Sum over all elems
    pub fn sum_all(&self) -> TensorResult<T> { self.flatten()?.sum(0, false)?.item() }

    /// Max elem in all elems 
    pub fn max_all(&self) -> TensorResult<T> { self.flatten()?.max(0, false)?.item() }

    /// Min elem in all elems 
    pub fn min_all(&self) -> TensorResult<T> { self.flatten()?.min(0, false)?.item() }

    /// Product over all elems
    pub fn prod_all(&self) -> TensorResult<T> { self.flatten()?.prod(0, false)?.item() }

    /// Index of the max elem along dim
    pub fn argmax(&self, dim: isize, keepdim: bool) -> TensorResult<Tensor<i64>> {
        self.reduce_with(dim, keepdim, |s| {
            let mut best = 0;
            for (i, &x) in s.iter().enumerate() { if x > s[best] { best = i; } }
            best as i64
        })
    }

    /// Index of the min elem along dim
    pub fn argmin(&self, dim: isize, keepdim: bool) -> TensorResult<Tensor<i64>> {
        self.reduce_with(dim, keepdim, |s| {
            let mut best = 0;
            for (i, &x) in s.iter().enumerate() { if x < s[best] { best = i; } }
            best as i64
        })
    }

    /// Mean of elems along dim
    pub fn mean(&self, dim: isize, keepdim: bool) -> TensorResult<Self> {
        let n = self.shape()[normalize_dim(dim, self.ndim())?];
        self.sum(dim, keepdim)?.div_scalar(T::from_f64(n as f64))
    }

    /// Mean of all elems
    pub fn mean_all(&self) -> TensorResult<T> { Ok(T::from_f64(self.sum_all()?.to_f64() / self.numel() as f64)) }

    /// Median along a dim
    pub fn median(&self, dim: isize, keepdim: bool) -> TensorResult<Self> { self.via_host(|t| t.reduce_with(dim, keepdim, |s| percentile_of(s, 50.0))) }

    /// Median of all elems 
    pub fn median_all(&self) -> TensorResult<T> { Ok(percentile_of(&self.host_data()?, 50.0)) }

    /// Quartile of elems across dim
    pub fn quartile(&self,dim:isize,qtile: Quartile) -> TensorResult<Tensor<T>>{
        let pct = match qtile{
            Quartile::Q1 => 25,
            Quartile::Q2 => 50,
            Quartile::Q3 => 75,
            Quartile::Q(x) => x.clamp(0, 100)
        } as f64;
        self.percentile(pct, dim, true)
    }

    /// Quartile of all elems
    pub fn quartile_all(&self,qtile: Quartile) -> TensorResult<T>{
        let pct = match qtile{
            Quartile::Q1 => 25,
            Quartile::Q2 => 50,
            Quartile::Q3 => 75,
            Quartile::Q(x) => x.clamp(0, 100)
        } as f64;
        self.percentile_all(pct)
    }
    // TODO:  p99,p95,p90

    /// Calculate range over dim 
    pub fn range(&self,dim:isize) -> TensorResult<Tensor<T>>{
        self.reduce_with(dim, true, |x| {
            let (mut mn,mut mx) = (T::highest(),T::lowest());
            x.iter().for_each(|k| {
                if *k > mx{ mx = *k; }
                if *k < mn{ mn = *k; }
            });
            mx - mn
        })
    }
    
    /// Calculate range over entire Tensor
    // FIXME: Make efficient now we do two passes
    pub fn range_all(&self) -> TensorResult<T>{ Ok(self.max_all()?.sub(self.min_all()?)) }

    /// Calculates IQR along a dim
    pub fn iqr(&self,dim: isize) -> TensorResult<Tensor<T>>{ self.quartile(dim, Quartile::Q3)?.sub(&self.quartile(dim, Quartile::Q1)?)}

    /// Calculates IQR across whole tensor
    pub fn iqr_all(&self) -> TensorResult<T>{Ok(self.quartile_all(Quartile::Q3)? - self.quartile_all(Quartile::Q1)?)}

    /// Percentile along a dim
    pub fn percentile(&self, p: f64, dim: isize, keepdim: bool) -> TensorResult<Self> { self.via_host(|t| t.reduce_with(dim, keepdim, |s| percentile_of(s, p))) }

    /// Percentile of all elems
    pub fn percentile_all(&self, p: f64) -> TensorResult<T> { Ok(percentile_of(&self.host_data()?, p)) }

    /// Most frequent value (smallest wins ties).
    pub fn mode(&self, dim: isize, keepdim: bool) -> TensorResult<Self> {self.via_host(|t| t.reduce_with(dim, keepdim, mode_of))}

    pub fn mode_all(&self) -> TensorResult<T> { Ok(mode_of(&self.host_data()?)) }
}


impl<T: Float> Tensor<T> {

    /// Variance along dim
    /// is_sample flag to choose if data is sample or population
    /// Population = N, Sample = N - 1 for counts
    pub fn var(&self, dim: isize, keepdim: bool, is_sample: bool) -> TensorResult<Self> {
        let n = self.shape()[normalize_dim(dim, self.ndim())?];
        let denom = if is_sample { n.saturating_sub(1) } else { n }.max(1);
        let centered = self.sub(&self.mean(dim, true)?)?;
        centered.square()?.sum(dim, keepdim)?.div_scalar(T::from_f64(denom as f64))
    }

    /// Std Deviation along dim
    /// is_sample flag to choose if data is sample or population
    /// Population = N, Sample = N - 1 for counts
    pub fn std(&self, dim: isize, keepdim: bool, is_sample: bool) -> TensorResult<Self> { self.var(dim, keepdim, is_sample)?.sqrt() }

    /// Variance taken across Tensor
    /// is_sample flag to choose if data is sample or population
    /// Population = N, Sample = N - 1 for counts
    pub fn var_all(&self, is_sample: bool) -> TensorResult<T> { self.flatten()?.var(0, false, is_sample)?.item() }

    /// Std Deviation taken across Tensor
    /// is_sample flag to choose if data is sample or population
    /// Population = N, Sample = N - 1 for counts
    pub fn std_all(&self, is_sample: bool) -> TensorResult<T> { Ok(self.var_all(is_sample)?.sqrt()) }

    /// Coeff of variation along dim
    /// is_sample flag to choose if data is sample or population
    /// Population = N, Sample = N - 1 for counts
    pub fn coeff_of_var(&self,dim:isize,is_sample:bool) -> TensorResult<Tensor<T>>{ self.std(dim, true, is_sample)?.div(&self.mean(dim, true)?)?.mul_scalar(T::from_f64(100.0)) }

    /// Coeff of variation across Tensor
    /// is_sample flag to choose if data is sample or population
    /// Population = N, Sample = N - 1 for counts
    pub fn coeff_of_var_all(&self,is_sample:bool) -> TensorResult<T>{ Ok(self.std_all(is_sample)?.div(self.mean_all()?).mul(T::from_f64(100.0))) }

    /// Magnitude of Tensor
    pub fn mag(&self) -> TensorResult<T> { Ok(self.square()?.sum_all()?.sqrt()) }

    /// Covariance of two equally sized tensors
    /// COV(x,y) = sum((xi - X)(yi - Y)) / N - 1
    pub fn cov(&self, other: &Self) -> TensorResult<T> {
        if self.numel() != other.numel() { return Err(TensorError::ShapeMismatch { op: "cov", lhs: self.shape().to_vec(), rhs: other.shape().to_vec() });}
        let (a, b) = (self.flatten()?, other.flatten()?);
        let (ma, mb) = (a.mean_all()?, b.mean_all()?);
        let prod = a.sub_scalar(ma)?.mul(&b.sub_scalar(mb)?)?;
        Ok(T::from_f64(prod.sum_all()?.to_f64() / (a.numel().max(2) - 1) as f64))
    }

    /// Correlation coefficient
    /// r = COV(X,Y) / std(X).std(Y)
    pub fn pearson(&self, other: &Self) -> TensorResult<T> { Ok(T::from_f64(self.cov(other)?.to_f64() / (self.std_all(true)?.to_f64() * other.std_all(true)?.to_f64()))) }
    pub fn corr(&self, other: &Self) -> TensorResult<T> { self.pearson(other) }

    /// Create Covariance Matrix for 2D tensor
    /// COV_MATRIX = C^T . C / N - 1
    /// C is centered tensor along dim 0
    pub fn cov_matrix(&self) -> TensorResult<Self> {
        if self.ndim() != 2 { return Err(TensorError::InvalidShape("Covariance matrix works for only 2D tensors ".into()));}
        let n = self.shape()[0];
        let centered = self.sub(&self.mean(0, true)?)?;
        centered.t()?.matmul(&centered)?.div_scalar(T::from_f64((n.max(2) - 1) as f64))
    }
    /// Create Correlation Matrix for 2D tensor
    /// CORR_MATRIX = C^T . C / N - 1
    pub fn corrcoef(&self) -> TensorResult<Self> {
        let c = self.cov_matrix()?;
        let d_mod = c.diag()?.sqrt()?;
        c.div(&d_mod.unsqueeze(1)?.mul(&d_mod.unsqueeze(0)?)?)
    }
    pub fn corr_mat(&self) -> TensorResult<Self> { self.corrcoef()}
    
    /// Calculate skewness of Tensor
    pub fn skewness(&self) -> TensorResult<T>{ Ok(self.sub_scalar(self.mean_all()?)?.div_scalar(self.std_all(true)?)?.powi32(3)?.sum_all()?.div(T::from_f64(self.numel() as f64))) }

    /// Calculate skewness of Tensor along dim
    pub fn skewness_all(&self,dim:isize,is_sample: bool) -> TensorResult<Tensor<T>>{self.sub(&self.mean(dim, true)?)?.div(&self.std(dim, true, is_sample)?)?.powi32(3)?.div_scalar(T::from_f64(self.numel() as f64))}

    /// Calculate kurtosis of Tensor along dim
    pub fn kurtosis_all(&self,dim:isize,is_sample: bool) -> TensorResult<Tensor<T>>{self.sub(&self.mean(dim, true)?)?.div(&self.std(dim, true, is_sample)?)?.powi32(4)?.div_scalar(T::from_f64(self.numel() as f64))}
    
    /// Calculate kurtosis of Tensor
    pub fn kurtosis(&self) -> TensorResult<T>{ Ok(self.sub_scalar(self.mean_all()?)?.div_scalar(self.std_all(true)?)?.powi32(4)?.sum_all()?.div(T::from_f64(self.numel() as f64))) }

}
