use crate::dtype::{Element, Float};
use crate::error::{TensorResult, TensorError};
#[cfg(feature = "cuda")]
use crate::layout::normalize_dim;
use crate::layout::{broadcast_shapes, Layout};
use crate::par;
use crate::storage::Storage;
use crate::tensor::Tensor;

impl<T: Element> Tensor<T> {

    /// Matrix multiplication 
    pub fn matmul(&self, rhs: &Self) -> TensorResult<Self> {
        self.same_device(rhs)?;
        if self.ndim() == 0 || rhs.ndim() == 0 { return Err(TensorError::InvalidShape("Matrix multiplication requires atleast 1D operands".into()));}
        let (sa, sb) = (self.ndim() == 1, rhs.ndim() == 1);
        // Since A(p,) B(p,) so to get output as 1x1 we unsqueeze them at diff dims so A(1,p) and B(p,1)  -> C(1,1)
        let a = if sa { self.unsqueeze(0)? } else { self.clone() };
        let b = if sb { rhs.unsqueeze(1)? } else { rhs.clone() };
        let (na, nb) = (a.ndim(), b.ndim());
        let (shape_a,shape_b) = (a.shape(),b.shape());
        let (m, k1) = (shape_a[na - 2], shape_a[na - 1]);
        let (k2, n) = (shape_b[nb - 2], shape_b[nb - 1]);
        if k1 != k2 { return Err(TensorError::ShapeMismatch { op: "Matmul", lhs: self.shape().to_vec(), rhs: rhs.shape().to_vec() });}
        let ret_shape = broadcast_shapes(&a.shape()[..na - 2], &b.shape()[..nb - 2])?; // Allocate a larger dim tensor exclusive of the two dims involved in matmul
        let out = match (&*a.storage, &*b.storage) {
            (Storage::Cpu(_), Storage::Cpu(_)) => cpu_matmul(&a, &b, &ret_shape, m, k1, n)?,
            #[cfg(feature = "cuda")]
            _ => crate::cuda::matmul(&a, &b, &ret_shape, m, k1, n)?,
        };
        let mut final_shape = ret_shape;
        if !sa { final_shape.push(m); }
        if !sb { final_shape.push(n); }
        out.reshape(&final_shape.iter().map(|x| *x as isize).collect::<Vec<isize>>())
    }
    
    pub fn dot(&self, rhs: &Self) -> TensorResult<Self> {
        if self.shape().last() != rhs.shape().last() || self.ndim() == 0 { return Err(TensorError::ShapeMismatch { op: "Dot", lhs: self.shape().to_vec(), rhs: rhs.shape().to_vec() });}
        self.mul(rhs)?.sum(-1, false)
    }

    /// Cross product of 3 vectors along the last dim (batch dims broadcast).
    /// Here the 3 vectors mean the last dim needs to have 3 elems
    // Generated by AI
    pub fn cross(&self, rhs: &Self) -> TensorResult<Self> {
        if self.shape().last() != Some(&3) || rhs.shape().last() != Some(&3) { return Err(TensorError::ShapeMismatch { op: "Cross", lhs: self.shape().to_vec(), rhs: rhs.shape().to_vec() });}
        let (a0, a1, a2) = (self.select(-1, 0)?, self.select(-1, 1)?, self.select(-1, 2)?);
        let (b0, b1, b2) = (rhs.select(-1, 0)?, rhs.select(-1, 1)?, rhs.select(-1, 2)?);
        let c0 = a1.mul(&b2)?.sub(&a2.mul(&b1)?)?;
        let c1 = a2.mul(&b0)?.sub(&a0.mul(&b2)?)?;
        let c2 = a0.mul(&b1)?.sub(&a1.mul(&b0)?)?;
        Tensor::stack(&[&c0, &c1, &c2], -1)
    }

    pub fn outer(&self, rhs: &Self) -> TensorResult<Self> {
        if self.ndim() != 1 || rhs.ndim() != 1 { return Err(TensorError::InvalidShape("Outer expects 1D tensors".into()));}
        self.unsqueeze(1)?.mul(&rhs.unsqueeze(0)?)
    }

    /// Used to convert 1D Tensor to 2D diagonal Tensor. eg: [1,2,4,5] -> [[1,0,0,0],[0,2,0,0],[0,0,4,0],[0,0,0,5]]
    /// Used to convert 2D Tensor to 1D Tensor by taking diagonal elems and converting them into single 1D. eg:  [[1,4,5,2],[9,2,20,13],[0,0,4,0],[9,4,5,5]] -> [1,2,4,5]
    pub fn diag(&self) -> TensorResult<Self> {
        self.via_host(|t| match t.ndim() {
            1 => {
                let n = t.numel();
                let v = t.to_vec()?;
                Ok(Tensor::from_fn(&[n, n], |ix| if ix[0] == ix[1] { v[ix[0]] } else { T::zero() }))
            }
            2 => {
                let n = t.shape()[0].min(t.shape()[1]);
                let d: Vec<T> = (0..n).map(|i| t.get(&[i, i])).collect::<TensorResult<_>>()?;
                Tensor::from_vec(d, &[n])
            }
            _ => Err(TensorError::InvalidShape("Diag expects 1D or 2D".into())),
        })
    }
    /// Get trace of a vector
    pub fn trace(&self) -> TensorResult<T> { 
        self.diag()?.sum_all() 
    }
}

/// Interior use function generated completely by AI 
fn cpu_matmul<T: Element>(a: &Tensor<T>, b: &Tensor<T>, batch: &[usize], m: usize, k: usize, n: usize) -> TensorResult<Tensor<T>> {
    let (na, nb) = (a.ndim(), b.ndim());
    
    let b = if b.strides()[nb - 1] != 1 && n > 1 { b.compact()? } else { b.clone() };
    let nb = b.ndim();

    let batch_offsets = |t: &Tensor<T>, nd: usize| -> TensorResult<Vec<usize>> {
        let l = Layout::new(t.shape()[..nd - 2].to_vec(), t.strides()[..nd - 2].to_vec(), t.offset())?;
        Ok(l.broadcast_to(batch)?.offsets().collect())
    };
    let a_offs = batch_offsets(a, na)?;
    let b_offs = batch_offsets(&b, nb)?;
    let (a_rs, a_cs) = (a.strides()[na - 2], a.strides()[na - 1]);
    let b_rs = b.strides()[nb - 2];
    let (sa, sb) = (a.storage.as_cpu().unwrap(), b.storage.as_cpu().unwrap());

    let total_batch: usize = batch.iter().product();
    let mut out = vec![T::zero(); total_batch * m * n];
    par::for_each_row(&mut out, n, k * n, |r, row| {
        let (bi, i) = (r / m, r % m);
        let (ao, bo) = (a_offs[bi] as isize, b_offs[bi] as isize);
        for p in 0..k {
            let aip = sa[(ao + i as isize * a_rs + p as isize * a_cs) as usize];
            let start = (bo + p as isize * b_rs) as usize;
            let brow = &sb[start..start + n];
            for j in 0..n {
                row[j] = row[j] + aip * brow[j];
            }
        }
    });
    let mut shape = batch.to_vec();
    shape.extend([m, n]);
    Tensor::from_vec(out, &shape)
}


/// Solve linear eqns using gauss jordan with resultant soln written to rhs and returns a determinant is soln is feasible
// Generated by AI
pub fn gauss_jordan<T: Float>(lhs: &mut [T], l_lhs: usize, rhs: &mut [T], l_rhs: usize) -> Option<T> {
    let mut det = T::one();
    let EPS = T::from_f64(0.001);
    for c in 0..l_lhs {
        let mut p = c;
        for r in c + 1..l_lhs {
            if lhs[r * l_lhs + c].abs() > lhs[p * l_lhs + c].abs() { p = r; }
        }


        if lhs[p * l_lhs + c].abs() <= EPS { return None; }
        if p != c {
            for j in 0..l_lhs { lhs.swap(c * l_lhs + j, p * l_lhs + j); }
            for j in 0..l_rhs { rhs.swap(c * l_rhs + j, p * l_rhs + j); }
            det = -det;
        }
        let piv = lhs[c * l_lhs + c];
        det = det * piv;
        for j in 0..l_lhs { lhs[c * l_lhs + j] = lhs[c * l_lhs + j] / piv; }
        for j in 0..l_rhs { rhs[c * l_rhs + j] = rhs[c * l_rhs + j] / piv; }
        for r in 0..l_lhs {
            if r == c { continue; }
            let f = lhs[r * l_lhs + c];
            if f.abs() <= EPS { continue; }
            for j in 0..l_lhs { lhs[r * l_lhs + j] = lhs[r * l_lhs + j] - f * lhs[c * l_lhs + j]; }
            for j in 0..l_rhs { rhs[r * l_rhs + j] = rhs[r * l_rhs + j] - f * rhs[c * l_rhs + j]; }
        }
    }
    Some(det)
}

impl<T: Float> Tensor<T> {

    /// Check if tensor is linear 
    pub fn is_linear_check(&self) -> TensorResult<usize> {
        if self.ndim() != 2 || self.shape()[1] != 1 { return Err(TensorError::InvalidShape(format!("Expected a linear Tensor, got {:?}", self.shape())));}
        Ok(self.shape()[0])
    }

    /// Check if tensor is square matrix
    pub fn is_square_check(&self) -> TensorResult<usize> {
        if self.ndim() != 2 || self.shape()[0] != self.shape()[1] { return Err(TensorError::InvalidShape(format!("Expected a square matrix, got {:?}", self.shape())));}
        Ok(self.shape()[0])
    }

    /// Check if tensor is cubic
    pub fn is_cubic_check(&self) -> TensorResult<usize>{
        if self.ndim() != 3 || (self.shape()[0] != self.shape()[1] && self.shape()[1] != self.shape()[2]) { return Err(TensorError::InvalidShape(format!("Expected a cubic matrix, got {:?}", self.shape())));}
        Ok(self.shape()[0])
    }

    /// Check if tensor is nthbic (Same size accross all n dims) 
    pub fn is_nthbic_check(&self) -> TensorResult<usize>{
        let shp = self.shape();
        if shp.chunks_exact(2).any(|x| {x[0] != x[1]}) { return Err(TensorError::InvalidShape(format!("Expected a nthbic Tensor, got {:?}", shp)));}
        Ok(shp[0])
    }

    /// Is tensor linear?
    pub fn is_linear(&self) -> bool {
        self.ndim() == 2 || self.shape()[1] == 1
    }

    /// Is tensor square?
    pub fn is_square(&self) -> bool{
        self.ndim() == 2 || self.shape()[0] == self.shape()[1]
    }

    /// Is tensor cubic?
    pub fn is_cubic(&self) -> bool{
        self.ndim() == 3 || (self.shape()[0] == self.shape()[1] && self.shape()[1] == self.shape()[2])
    }

    /// Is tensor nthbic?
    pub fn is_nthbic(&self) -> bool{
        self.shape().chunks_exact(2).all(|x| {x[0] == x[1]})
    }

    /// Solve for X in AX = B using gauss_jordan 
    pub fn solve(&self, b: &Self) -> TensorResult<Self> {
        self.same_device(b)?;
        let n = self.is_square_check()?;
        let vec_rhs = b.ndim() == 1;
        let b2 = if vec_rhs { b.unsqueeze(1)? } else { b.clone() };
        if b2.ndim() != 2 || b2.shape()[0] != n { return Err(TensorError::ShapeMismatch { op: "solve", lhs: self.shape().to_vec(), rhs: b.shape().to_vec() });}
        let m = b2.shape()[1];
        let mut av = self.to_vec()?;
        let mut bv = b2.to_vec()?;
        gauss_jordan(&mut av, n, &mut bv, m).ok_or_else(|| TensorError::Unsupported("Matrix is singular".into()))?;
        let x = Tensor::from_vec(bv, &[n, m])?.to_device(self.device())?;
        if vec_rhs { x.squeeze(1) } else { Ok(x) }
    }

    /// Computes the inverse of Tensor using [A|I] -> [I|A^-1]
    pub fn inv(&self) -> TensorResult<Self> {
        let n = self.is_square_check()?;
        self.solve(&Tensor::<T>::eye(n).to_device(self.device())?)
    }

    /// Compute determinant of the matrix
    pub fn det(&self) -> TensorResult<T> {
        let n = self.is_square_check()?;
        let mut av = self.to_vec()?;
        Ok(gauss_jordan(&mut av, n, &mut vec![], 0).unwrap_or_else(T::zero))
    }
    
    /// Computes nth degree normal of Tensor
    /// 1st degree -> sum(|xi|) 
    /// 2nd degree -> (sum(|xi|^2))^1/2
    /// nth degree -> (sum(|xi|^n))^1/n
    /// inf degree -> max(|xi|)
    // Inf degree, support for p to be f64,and optimisation branch p = 1 and 2 suggested by AI
    pub fn norm(&self, p: f64, dim: isize, keepdim: bool) -> TensorResult<Self> {
        let a = self.abs()?;
        if p.abs() <= 0.01{ return Err(TensorError::Custom(format!("Norm of {} is too close to zero and wil lead to unstable exponentiation",p)))}
        if p.is_infinite() { a.max(dim, keepdim) }
        else if p == 1.0 { a.sum(dim, keepdim) }
        else if p == 2.0 { self.square()?.sum(dim, keepdim)?.sqrt() }
        else { a.powf(T::from_f64(p))?.sum(dim, keepdim)?.powf(T::from_f64(1.0 / p)) }
    }

    /// L2 norm along dim
    pub fn normalize(&self, dim: isize) -> TensorResult<Self> {
        let n = self.norm(2.0, dim, true)?.add_scalar(T::from_f64(1e-12))?;
        self.div(&n)
    }

    /// Cosine Similarity between two vectors
    pub fn cosine_similarity(&self, rhs: &Self, dim: isize) -> TensorResult<Self> {
        self.normalize(dim)?.mul(&rhs.normalize(dim)?)?.sum(dim, false)
    }

    /// Softmax of Tensor
    pub fn softmax(&self, dim: isize) -> TensorResult<Self> {
        match &*self.storage {
            Storage::Cpu(_) => {
                let e = self.sub(&self.max(dim, true)?)?.exp()?;
                e.div(&e.sum(dim, true)?)
            }
            #[cfg(feature = "cuda")]
            Storage::Cuda(_) => crate::cuda::softmax(self, normalize_dim(dim, self.ndim())?),
        }
    }

    /// Log of sum of base e exponentials stabily 
    // Find the largest elem and then sub all the elems by this max and use it for so we avoid exponential growth
    pub fn logsumexp(&self, dim: isize, keepdim: bool) -> TensorResult<Self> {
        let m = self.max(dim, true)?;
        // Convert log(e^n-1 + e^n + e^n+1) -> n + log(e^-1+ e^0 + e^1)
        let lse = self.sub(&m)?.exp()?.sum(dim, true)?.ln()?.add(&m)?;
        if keepdim { Ok(lse) } else { lse.squeeze(dim) }
    }

    /// Logsoftmax of Tensor
    pub fn log_softmax(&self, dim: isize) -> TensorResult<Self> {
        self.sub(&self.logsumexp(dim, true)?)
    }

    /// Normalize over the last dim(mean = 0,var = 1)
    pub fn layer_norm(&self, eps: T) -> TensorResult<Self> {
        match &*self.storage {
            Storage::Cpu(_) => {
                let (mean,var) = (self.mean(-1, true)?,self.var(-1, true, false)?);
                self.sub(&mean)?.div(&var.add_scalar(eps)?.sqrt()?)
            }
            #[cfg(feature = "cuda")]
            Storage::Cuda(_) => crate::cuda::layer_norm(self, eps),
        }
    }
    
    /// Calculate the distance between two Tensors using p dim normalised distance
    pub fn pdim_dist(&self,other: Tensor<T>,p:f64,dim:isize,keepdim: bool) -> TensorResult<Self>{
        self.same_device(&other)?;
        self.sub(&other)?.norm(p, dim, keepdim)
    }

    /// Calculate the manhatten distance between two tensors
    pub fn manhatten(&self,other: Tensor<T>,dim:isize) -> TensorResult<Self>{
        self.same_device(&other)?;
        self.sub(&other)?.norm(1.0, dim, true)   
    }

    /// Calculate the euclidean distance between two tensors
    pub fn euclidean(&self,other: Tensor<T>,dim:isize) -> TensorResult<Self>{
        self.same_device(&other)?;
        self.sub(&other)?.norm(2.0, dim, true)   
    }

}
