// CUDA backend using cudarc, kernels are compiled at runtime with NVRTC.
// Mostly generated by AI

mod kernels;
use Utilities::device::Device::Device;
use crate::dtype::Element;
use crate::error::{Result, TensorError};
use crate::layout::Layout;
use crate::ops_elementwise::{BinaryOp, UnaryOp};
use crate::ops_stats::ReduceOp;
use crate::storage::Storage;
use crate::tensor::Tensor;
use cudarc::driver::{CudaContext, CudaFunction, CudaModule, CudaSlice, CudaStream, LaunchConfig, PushKernelArg};
use cudarc::nvrtc::compile_ptx;
use std::collections::HashMap;
use std::fmt;
use std::sync::{Arc, Mutex, OnceLock};

pub fn cu<E: fmt::Display>(e: E) -> TensorError {
    TensorError::Cuda(e.to_string())
}

/// Each GPU with its kernel module
pub struct Gpu {
    pub ctx: Arc<CudaContext>,
    pub stream: Arc<CudaStream>,
    modules: Mutex<HashMap<String, Arc<CudaModule>>>,
}

/// Returns the Gpu if exist else adds to map and returns
fn device(ordinal: usize) -> Result<Arc<Gpu>> {
    static DEVICES: OnceLock<Mutex<HashMap<usize, Arc<Gpu>>>> = OnceLock::new();
    let mut g = DEVICES.get_or_init(Default::default).lock().unwrap();
    if let Some(d) = g.get(&ordinal) {
        return Ok(d.clone());
    }
    let ctx = CudaContext::new(ordinal).map_err(cu)?;
    let stream = ctx.default_stream();
    let d = Arc::new(Gpu { ctx, stream, modules: Mutex::new(HashMap::new()) });
    g.insert(ordinal, d.clone());
    Ok(d)
}

/// Cuda memory
pub struct CudaStorage<T: Element> {
    pub data: CudaSlice<T>,
    pub dev: Arc<Gpu>,
    pub ordinal: usize,
}

impl<T: Element> fmt::Debug for CudaStorage<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "CudaStorage<{}>(len={}, device={})", T::NAME, self.len(), self.ordinal)
    }
}

impl<T: Element> CudaStorage<T> {
    /// Len of data
    pub fn len(&self) -> usize { 
        self.data.len() 
    }

    /// Move host data to Gpu device
    pub fn from_host(host: &[T], ordinal: usize) -> Result<Self> {
        if T::CUDA_TYPE.is_none() { return Err(TensorError::Unsupported(format!("Type {} is not supported on CUDA", T::NAME)));}
        let dev = device(ordinal)?;
        let data = if host.is_empty() {
            dev.stream.alloc_zeros::<T>(1).map_err(cu)?
        } else {
            dev.stream.clone_htod(host).map_err(cu)?
        };
        Ok(CudaStorage { data, dev, ordinal })
    }

    /// Move data to Cpu
    pub fn to_host(&self) -> Result<Vec<T>> {
        self.dev.stream.clone_dtoh(&self.data).map_err(cu)
    }
}

/// Make a cuda kernel module and return a reference to CudaFunction by name
pub fn func<T: Element>(dev: &Arc<Gpu>, name: &str) -> Result<CudaFunction> {
    let key = format!("TsoR_{}", T::NAME); // Module name
    let module = {
        let mut g = dev.modules.lock().unwrap();
        if let Some(m) = g.get(&key) {
            m.clone()
        } else {
            let ctype = T::CUDA_TYPE.ok_or_else(|| TensorError::Unsupported(format!("{} on CUDA", T::NAME)))?;
            let ptx = compile_ptx(kernels::source(ctype)).map_err(cu)?;
            let m = dev.ctx.load_module(ptx).map_err(cu)?;
            g.insert(key, m.clone());
            m
        }
    };
    module.load_function(name).map_err(|e| cu(format!("Function `{name}` not found in kernel: {e}")))
}

/// Returns the CudaStorage of Tensor if on Gpu
pub fn cstore<T: Element>(t: &Tensor<T>) -> Result<&CudaStorage<T>> {
    match &*t.storage {
        Storage::Cuda(c) => Ok(c),
        _ => Err(TensorError::DeviceMismatch { lhs: t.device(), rhs: Device::Cuda(0) }),
    }
}

/// Builds Tensor of shape on the device of Cudastorage
pub fn wrap<T: Element>(data: CudaSlice<T>, like: &CudaStorage<T>, shape: &[usize]) -> Tensor<T> {
    let s = CudaStorage { data, dev: like.dev.clone(), ordinal: like.ordinal };
    Tensor::from_comp(Storage::Cuda(s), Layout::contiguous(shape))
}

/// Make a Zeroed out Gpu Storage slice of size n
fn alloc<T: Element>(c: &CudaStorage<T>, n: usize) -> Result<CudaSlice<T>> { c.dev.stream.alloc_zeros::<T>(n.max(1)).map_err(cu) }

/// Materialize any strided/broadcast/offset view into a dense buffer on the device
// Generated using AI
pub fn compact<T: Element>(t: &Tensor<T>) -> Result<Tensor<T>> {
    let c = cstore(t)?;
    let (n, nd) = (t.numel(), t.ndim());
    let mut out = alloc(c, n)?;
    if n > 0 {
        let shape: Vec<i64> = if nd == 0 { vec![1] } else { t.shape().iter().map(|&s| s as i64).collect() };
        let strides: Vec<i64> = if nd == 0 { vec![0] } else { t.strides().iter().map(|&s| s as i64).collect() };
        let shape_d = c.dev.stream.clone_htod(&shape).map_err(cu)?;
        let strides_d = c.dev.stream.clone_htod(&strides).map_err(cu)?;
        let off = t.offset();
        let f = func::<T>(&c.dev, "strided_copy")?;
        let mut b = c.dev.stream.launch_builder(&f);
        b.arg(&mut out).arg(&c.data).arg(&n).arg(&nd).arg(&shape_d).arg(&strides_d).arg(&off);
        unsafe { b.launch(LaunchConfig::for_num_elems(n as u32)) }.map_err(cu)?;
    }
    Ok(wrap(out, c, t.shape()))
}

/// Apply UnaryOp on tensor on Gpu
pub fn unary<T: Element>(t: &Tensor<T>, op: UnaryOp) -> Result<Tensor<T>> {
    let t = t.compact()?;
    let c = cstore(&t)?;
    let n = t.numel();
    let mut out = alloc(c, n)?;
    if n > 0 {
        let opi = op as i32;
        let f = func::<T>(&c.dev, "unary_k")?;
        let mut b = c.dev.stream.launch_builder(&f);
        b.arg(&mut out).arg(&c.data).arg(&n).arg(&opi);
        unsafe { b.launch(LaunchConfig::for_num_elems(n as u32)) }.map_err(cu)?;
    }
    Ok(wrap(out, c, t.shape()))
}

/// Apply BinaryOp on tensor on Gpu
pub fn binary<T: Element>(a: &Tensor<T>, b: &Tensor<T>, op: BinaryOp, out_shape: &[usize]) -> Result<Tensor<T>> {
    let a = a.broadcast_to(out_shape)?.compact()?;
    let b = b.broadcast_to(out_shape)?.compact()?;
    let (ca, cb) = (cstore(&a)?, cstore(&b)?);
    let n = a.numel();
    let mut out = alloc(ca, n)?;
    if n > 0 {
        let opi = op as i32;
        let f = func::<T>(&ca.dev, "binary_k")?;
        let mut bl = ca.dev.stream.launch_builder(&f);
        bl.arg(&mut out).arg(&ca.data).arg(&cb.data).arg(&n).arg(&opi);
        unsafe { bl.launch(LaunchConfig::for_num_elems(n as u32)) }.map_err(cu)?;
    }
    Ok(wrap(out, ca, out_shape))
}
/// Matrix mult on Gpu
// Generated by AI
pub fn matmul<T: Element>(a: &Tensor<T>, b: &Tensor<T>, batch: &[usize], m: usize, k: usize, n: usize) -> Result<Tensor<T>> {
    let mut sa = batch.to_vec();
    sa.extend([m, k]);
    let mut sb = batch.to_vec();
    sb.extend([k, n]);
    let a = a.broadcast_to(&sa)?.compact()?;
    let b = b.broadcast_to(&sb)?.compact()?;
    let (ca, cb) = (cstore(&a)?, cstore(&b)?);
    let nb: usize = batch.iter().product();
    let mut out = alloc(ca, nb * m * n)?;
    if nb * m * n > 0 {
        let f = func::<T>(&ca.dev, "matmul_k")?;
        let cfg = LaunchConfig {
            grid_dim: (((n + 15) / 16) as u32, ((m + 15) / 16) as u32, nb as u32),
            block_dim: (16, 16, 1),
            shared_mem_bytes: 0,
        };
        let mut bl = ca.dev.stream.launch_builder(&f);
        bl.arg(&mut out).arg(&ca.data).arg(&cb.data).arg(&m).arg(&k).arg(&n);
        unsafe { bl.launch(cfg) }.map_err(cu)?;
    }
    let mut shape = batch.to_vec();
    shape.extend([m, n]);
    Ok(wrap(out, ca, &shape))
}

pub fn reduce<T: Element>(t: &Tensor<T>, dim: usize, op: ReduceOp, keepdim: bool) -> Result<Tensor<T>> {
    let cols = t.shape()[dim];
    if cols == 0 || t.numel() == 0 {
        return t.via_host(|h| match op {
            ReduceOp::Sum => h.sum(dim as isize, keepdim),
            ReduceOp::Max => h.max(dim as isize, keepdim),
            ReduceOp::Min => h.min(dim as isize, keepdim),
        });
    }
    let moved = t.movedim_last(dim)?.compact()?;
    let c = cstore(&moved)?;
    let rows = moved.numel() / cols;
    let mut out_shape = t.shape().to_vec();
    out_shape.remove(dim);
    let mut out = alloc(c, rows)?;
    const BLOCK: u32 = 256;
    let cfg = LaunchConfig {
        grid_dim: (rows as u32, 1, 1),
        block_dim: (BLOCK, 1, 1),
        shared_mem_bytes: BLOCK * std::mem::size_of::<T>() as u32,
    };
    let init = match op { ReduceOp::Sum => T::zero(), ReduceOp::Max => T::lowest(), ReduceOp::Min => T::highest() };
    let opi = op as i32;
    let f = func::<T>(&c.dev, "reduce_k")?;
    let mut b = c.dev.stream.launch_builder(&f);
    b.arg(&mut out).arg(&c.data).arg(&cols).arg(&opi).arg(&init);
    unsafe { b.launch(cfg) }.map_err(cu)?;
    let r = wrap(out, c, &out_shape);
    if keepdim { r.unsqueeze(dim as isize) } else { Ok(r) }
}
